# Generated by Django 5.0.1 on 2025-11-28 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ブロック日時')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='理由')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='ブロックされた人')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL, verbose_name='ブロックした人')),
            ],
            options={
                'verbose_name': 'ブロック',
                'verbose_name_plural': 'ブロック',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='blog_block_blocker_80ce19_idx'), models.Index(fields=['-created_at'], name='blog_block_created_79160c_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
